# My aliases
alias cls='clear'
alias r='rm -rfv'
alias ll='ls -las'
alias m='more'
alias v='vi'
alias vg='vagrant'
alias vup='vagrant up && vagrant ssh'
alias mvim='/usr/local/opt/macvim/bin/mvim'
alias vh='vagrant halt && vagrant status'
alias vh!='vagrant halt && vagrant status && rm -rfv ~/VirtualBox\ VMs/'
alias grab='sudo apt-get update && sudo apt-get install -qq'
alias goodnight='gksudo shutdown -P now'
alias tarup='tar -czf'
alias tardown='tar -xvf'
alias tarpeek='tar -tvf'
alias eject='drutil tray eject'
alias htop='sudo htop'
