# My aliases
alias r='rm -rfv'
alias l='ls -las'
alias v='vi'
alias vg='vagrant'
alias vup='vagrant up && vagrant ssh'
alias vh='vagrant halt && vagrant status'
alias mvm='/Applications/MacVim.app/Contents/MacOS/MacVim'
alias grab='sudo apt-get update && sudo apt-get install -qq'
alias goodnight='gksudo shutdown -P now'
alias tarup='tar -czf'
alias tardown='tar -xvf'
alias tarpeek='tar -tvf'
alias eject='drutil tray eject'
