#!/bin/sh
echo Must have curl and git installed. 
read
cp -v .gitconfig ~
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
cp -v .zshrc ~
cp -v .tmux.conf ~
cp -v .vimrc ~
cp -v .bashrc ~
cp -v .bash_aliases ~
echo Bootstraped.
exit
