#!/bin/bash
echo "Pushing changes in ~ to dots/master"
cd ~/dots
cp -v ~/.zshrc .
cp -v ~/.tmux.conf .
cp -v ~/.vimrc.after .
cp -v ~/.bashrc .
cp -v ~/.bash_aliases .
echo "Committing..."
git add .
git commit
git push origin master
exit
