#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/tm/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
fbsetbg -l &
nm-applet &
conky &
synclient PalmDetect=1 HorizTwoFingerScroll=1 &
lightum -w 1 &
synapse -s &
transmission-gtk -m &
dropbox start &
# nautilus --no-desktop &
/home/tm/Dropbox/scripts/enable_compositing.sh &


# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/tm/.fluxbox/log"
